name: auto
on:
  schedule:
  - cron: "0 2 * * *" # 每天10点执行 UTC+8

  # 可在github操作选项卡手动运行flag
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v6
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: python run.py
      - uses: EndBug/add-and-commit@v9
        with:
          author_name: DDullahan
          author_email: DDullahan@163.com
          message: 'Auto Commit'
